name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Dependency Security Scan
        run: pip-audit

  build:
    name: Build Docker Image
    needs:
      - gitleaks
      - dependency-scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t securedeploy:latest .
