name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pip-audit
        run: python -m pip install pip-audit

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pip-audit
        run: pip-audit


  build:
    name: Build Docker Image
    needs:
      - gitleaks
      - dependency-scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t securedeploy:latest .


  trivy:
    name: Trivy Container Security Scan
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t securedeploy:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "securedeploy:latest"
          format: "table"
          severity: "HIGH,CRITICAL"
          exit-code: "0"

      - name: Generate Trivy JSON report
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image \
            --format json \
            -o trivy-report.json \
            securedeploy:latest

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.json
